---
title: "Replication of Not Learning From Failure - the Greatest Failure of All by Lauren Eskreis-Winkler (2019, Psychological Science)"
author: "Nicholas Hiser (nhiser@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

  I have chosen this replication because of the potentially wide application its results can have on everyday life. I have dealt with a number of learning challenges in my undergraduate career and the findings of Eskreis-Winkler et al. provide insight as to how I came to experience such difficulty. The results indicate that negative feedback can impair an individual's learning. The researchers were able to make this determination through the implementation of more than five studies with varying sample size and experimental conditions. I intend to replicate Study 2a where a negative feedback group had their learning results compared to a group that received positive feedback. I relate to these results because I have been engaged in daily psychotherapy since 2018 and have learned that I have the tendency to magnify my mistakes. I produce negative feedback within myself and it has seemed to contribute to academic struggle. I find it curious Eskreis-Winkler et al. have theorized and seemingly proved that negative feedback does impair learning.
  
  The experiment in Study 2a was performed using 100 qualified participants from Amazon Mechanical Turk. The original qualification for participants was an approval rate of 50% or more. The stimuli consisted of two rounds of three questions asking participants to make linguistic inferences for novel, researcher generated symbols. The first round served as a learning phase and the second phase featured the same answers with the wording of the question reversed. Each question featured a binary choice of answers for the meaning of the novel characters. Only one answer is correct and the participants have to choose which they believe matches the meaning of the character. Participants were prompted to answer a text box question at the start of their assessment in order to ensure their commitment to the task. An incentive was also established at this point by informing participants there would be a $0.10 bonus for each correct answer in the second round. Participants are chosen at random to enter the  negative feedback condition or positive feedback condition. Participants were either informed of their incorrect answer or their correct answer after answering each question. Then, participants are prompted by another text entry before the start of round 2 as a distraction. Participants answer the questions again, though in this round the phrasing of the questions changes to force participants to make an inference based on their feedback from the first round. 
    
  I anticipate finding enough participants could be challenging as well as ensuring proper split between negative and positive feedback group sample sizes. Providing the bonus for correct answers in the second round will be difficult to implement. The incentive for providing correct answers could be crucial for participant engagement. The initial study had a small bonus ($0.10) for this and a larger amount could lead to more engagement with the learning phase. 

Repository: https://github.com/psych251/Eskreis-Winkler2019.git

Original paper: https://github.com/psych251/Eskreis-Winkler2019/blob/main/original_paper/Eskreis-Winkler(2019).pdf

##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
